// Code generated by MockGen. DO NOT EDIT.
// Source: writer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dto "sahaj/flight/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// WriteInvalidTickets mocks base method.
func (m *MockWriter) WriteInvalidTickets(tickets []dto.InvalidTicketCSV) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteInvalidTickets", tickets)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteInvalidTickets indicates an expected call of WriteInvalidTickets.
func (mr *MockWriterMockRecorder) WriteInvalidTickets(tickets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteInvalidTickets", reflect.TypeOf((*MockWriter)(nil).WriteInvalidTickets), tickets)
}

// WriteValidTickets mocks base method.
func (m *MockWriter) WriteValidTickets(tickets []dto.ValidTicketCSV) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteValidTickets", tickets)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteValidTickets indicates an expected call of WriteValidTickets.
func (mr *MockWriterMockRecorder) WriteValidTickets(tickets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteValidTickets", reflect.TypeOf((*MockWriter)(nil).WriteValidTickets), tickets)
}
